CREATE TABLE categories(
 id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 category VARCHAR(40) NOT NULL,
);


CREATE TABLE pastas (
 id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(40) NOT NULL,
 description VARCHAR(350) NOT NULL,
 category REFERENCES categories (id),
 weight integer,
 cooking_time integer,
 image VARCHAR(30),
price integer,
);


INSERT INTO users
(name, description, category, weight, cooking_time, image, price)
VALUES
('Rigatoni', 'Rigatoni, which comes from the word “rigato” meaning ridged, are short, wide tubes of pasta that have ridges on the outside, but are smooth on the inside. Rigatoni are perfect for big chunkier sauces as their ridges and wide center help capture the sauce perfectly. This also helps them contain meats and large vegetables.', ),
('Tagliatelle all"uovo', 'Tagliatelle is an egg-dough-based long, ribbon shaped pasta. Tagliatelle pair really well with chunky sauces, like ragù alla bolognese.', );