import Head from 'next/head';
import Link from 'next/link';
import styled from 'styled-components';
import Layout from '../../components/Layout';

const ThankYouContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const ThankYouTitle = styled.h1`
  font-family: 'Playfair Display', serif;
  font-weight: 900;
  color: #2f3b4d;
  font-size: 2.5rem;
  margin-top: 128px;
`;

const GoingBackLink = styled.a`
  background-color: #faf7f6;
  border: 2px solid;
  text-align: center;
  text-decoration: underline 2px solid transparent;
  transition: 0.5s;
  border-color: #2f3b4d;
  color: #5c5c5c;
  font-family: 'Work Sans', sans-serif;
  width: 240px;
  margin-top: 12px;
  padding: 8px 12px 6px;
  cursor: pointer;
  :hover {
    text-decoration: underline 2px solid #2f3b4d;
  }
`;

interface AboutProps {
  cartItemsNumber: number;
}

function PurchaseSuccess({ cartItemsNumber }: AboutProps) {
  return (
    <Layout cartItemsNumber={cartItemsNumber}>
      <Head>
        <title>Thank you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/farfalle.png" />
      </Head>
      <ThankYouContainer>
        <ThankYouTitle>Thank you for your purchase!</ThankYouTitle>
        <Link href="/" passHref>
          <GoingBackLink>Go back to our shop</GoingBackLink>
        </Link>
      </ThankYouContainer>
    </Layout>
  );
}

export default PurchaseSuccess;
