import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import Layout from '../../components/Layout';
import PastaItem from '../../components/PastaItem';
import { pastasType, pastaType } from '../../util/database';

const PastaProductsContainer = styled.div`
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  margin-top: 64px;
  margin-left: 64px;
`;

const ProductsHead = styled.h1`
  font-family: 'Playfair Display', serif;
  color: #2f3b4d;
  font-weight: 900;
  font-size: 3rem;
  text-align: center;
`;
interface ProductsProps {
  pastas: pastasType;
  cartItemsNumber: number;
}

const products: NextPage<ProductsProps> = ({ pastas, cartItemsNumber }) => {
  return (
    <Layout cartItemsNumber={cartItemsNumber}>
      <Head>
        <title>Our products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/farfalle.png" />
      </Head>
      <ProductsHead>Our world of pastabilities</ProductsHead>
      <PastaProductsContainer>
        {pastas.map((pasta: pastaType) => {
          return <PastaItem pasta={pasta} key={pasta.id} />;
        })}
      </PastaProductsContainer>
    </Layout>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // get data from API
  const { pastas } = await import('../../util/database');
  return {
    props: {
      pastas,
    },
  };
};

export default products;
