import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import Layout from '../../components/Layout';
import PastaItem from '../../components/PastaItem';
import { pastasType, pastaType } from '../../util/database';

const PastaProductsContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  margin-left: 64px;
`;
interface productsProps {
  pastas: pastasType;
}
[];

const Products: NextPage<productsProps> = ({ pastas }) => {
  return (
    <Layout>
      <Head>
        <title>Our products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PastaProductsContainer>
        {pastas.map((pasta: pastaType) => {
          return <PastaItem pasta={pasta} key={pasta.id} />;
        })}
      </PastaProductsContainer>
    </Layout>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // get data from API
  const { pastas } = await import('../../util/database');
  return {
    props: {
      pastas,
    },
  };
};

export default Products;
