import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../../components/Layout';

const About: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span>about page</span>
    </Layout>
  );
};

export default About;
